### ISSUE TITLE
Test & Maybe Release workflow fails

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs-dist-indexer#32]
https://github.com/nodejs/nodejs-dist-indexer/actions/runs/10945041013/job/30388356592

```
[4:26:32 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/nodejs/nodejs-dist-indexer.git
[4:26:33 PM] [semantic-release] › ✘  The command "git push --dry-run --no-verify https://x-access-token:[secure]@github.com/nodejs/nodejs-dist-indexer.git HEAD:main" failed with the error message remote: Permission to nodejs/nodejs-dist-indexer.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/nodejs/nodejs-dist-indexer.git/': The requested URL returned error: 403.
[4:26:33 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[4:26:33 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
Request quota exhausted for request GET /search/issues
Request quota exhausted for request GET /search/issues
Request quota exhausted for request GET /search/issues
Request quota exhausted for request GET /search/issues
Request quota exhausted for request GET /search/issues
[4:30:35 PM] [semantic-release] › ✘  Failed step "fail" of plugin "@semantic-release/github"
[4:30:35 PM] [semantic-release] › ✘  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID A440:1225:17[24](https://github.com/nodejs/nodejs-dist-indexer/actions/runs/10945041013/job/30388356592#step:7:25)90:1757B1:66EC51AA. - https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits
    at fetchWrapper (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/@octokit/request/dist-bundle/index.js:119:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
    at async Job.doExecute (/home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=in%3Atitle+repo%3Anodejs%2Fnodejs-dist-indexer+type%3Aissue+state%3Aopen+The%20automated%20release%20is%20failing%20%F0%9F%9A%A8',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': '@semantic-release/github v10.3.4 octokit-core.js/6.1.2 Node.js/20.17.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: undefined,
      hook: [Function: bound bound register],
      retryCount: 3
    }
  },
  response: {
    url: 'https://api.github.com/search/issues?q=in%3Atitle+repo%3Anodejs%2Fnodejs-dist-indexer+type%3Aissue+state%3Aopen+The%20automated%20release%20is%20failing%20%F0%9F%9A%A8',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 19 Sep 2024 16:30:34 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'A440:12[25](https://github.com/nodejs/nodejs-dist-indexer/actions/runs/10945041013/job/30388356592#step:7:26):172490:1757B1:66EC51AA',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '30',
      'x-ratelimit-reset': '17[26](https://github.com/nodejs/nodejs-dist-indexer/actions/runs/10945041013/job/30388356592#step:7:27)763494',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID A440:1225:172490:1757B1:66EC51AA.'
    }
  },
  pluginName: '@semantic-release/github'
}
[4:30:35 PM] [semantic-release] › ✘  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch main on the remote Git repository with URL https://x-access-token:[secure]@github.com/nodejs/nodejs-dist-indexer.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at default (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/semantic-release/index.js:101:11)
    at async Module.default (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/semantic-release/index.js:[27](https://github.com/nodejs/nodejs-dist-indexer/actions/runs/10945041013/job/30388356592#step:7:28)8:22)
    at async default (file:///home/runner/work/nodejs-dist-indexer/nodejs-dist-indexer/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `main` on the remote Git repository with URL `https://x-access-token:[secure]@github.com/nodejs/nodejs-dist-indexer.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}
Error: Process completed with exit code 1.
```

**Comment by richardlau** [comment]
Suspect this is fallout from the org changes (https://github.com/nodejs/admin/issues/905) and we'll probably need to add permissions in the workflow file for the token.
